# On a merge/commit to main, this will perform a release and will publish a package to GitHub and NPM

name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Display Version of `npm`
      run: npm -v
    - name: Clean Cache
      run: npm cache clean --force
    - name: Install Dependencies
      run: npm ci
    - name: Install Extra Plugins for `semantic-release`
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git      
    - name: Build
      env:
        CI: false
      run: npm run build    
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_PACKAGE_TOKEN }}
      run: npx semantic-release
